name: Tests
on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    types: [synchronize, opened, edited]
    paths-ignore:
      - '**.md'
jobs:
  skip:
    name: Check Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{steps.skip-check.outputs.should_skip}}
    steps:
      - name: Skip Duplicate Actions (Build and Test)
        uses: fkirc/skip-duplicate-actions@f75dd6564bb646f95277dc8c3b80612e46a4a1ea # tag=v3
        id: skip-check
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: skip
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Setup Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # tag=v3
        with:
          go-version: 1.17
      - name: Find Module Cache Directory
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-mod-cache
      - name: Restore Module Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
        with:
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: ${{ steps.go-mod-cache.outputs.dir }}
      - name: Update Dependencies
        run: go mod download
      - name: Build
        run: go build -v ${{github.workspace}}
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: skip
    strategy:
      fail-fast: false
      matrix:
        terraform: ['1.0.5']
        os: [ubuntu-latest, windows-latest, macos-latest]
    if: needs.skip.outputs.should-skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - name: Setup Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # tag=v3
        with:
          go-version: 1.17
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # tag=v1
        with:
          terraform_version: ${{ matrix.terraform }}
      - name: Get Go Modules Cache Location
        run: echo "::set-output name=dir::$(go env GOMODCACHE)"
        id: go-modules-cache
      - name: Get Go Build Cache Location
        run: echo "::set-output name=dir::$(go env GOCACHE)"
        id: go-build-cache
      - name: Restore Module Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
        with:
          restore-keys: ${{ runner.os }}-go-
          path: ${{ steps.go-modules-cache.outputs.dir }}
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
      - name: Restore Build Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
        with:
          restore-keys: ${{ runner.os }}-go-build-
          path: ${{ steps.go-build-cache.outputs.dir }}
          key: ${{ runner.os}}-go-build-${{ hashFiles('**/go.mod', '**/go.sum') }}
      - name: Update Dependencies
        run: go mod download
      - name: Terraform Acceptance Tests
        run: >-
          go test -v
          -race
          -coverprofile coverage.out
          -covermode=atomic
          -cover ${{github.workspace}}/improvmx
        env:
          TF_ACC: 1
      - name: Upload Code Coverage
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # tag=v2.1.0
        with:
          fail_ci_if_error: true
          directory: ${{ github.workspace }}
          files: coverage.out
